[tool.poetry]
name = "vulnerability-scanner"
version = "0.1.0"
description = ""
authors = ["lijoabraham1234@gmail.com"]
readme = "README.md"
packages = [{include = "vulnerability_scanner"}]

[tool.poetry.dependencies]
python = "3.12.2"
uvicorn = "^0.27.1"
sqlalchemy = "^2.0.27"
alembic = "^1.13.1"
psycopg2 = "^2.9.9"
pydantic = "^2.6.1"
python-dotenv = "^1.0.1"
fastapi = "^0.109.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
