[tool.poetry]
name = "vulnerability-scanner"
version = "0.1.0"
description = ""
authors = ["lijoabraham1234@gmail.com"]
readme = "README.md"
packages = [{include = "vulnerability_scanner"}]

[tool.poetry.dependencies]
python = "3.12.2"
uvicorn = "^0.27.1"
sqlalchemy = "^2.0.27"
alembic = "^1.13.1"
psycopg2 = "^2.9.9"
pydantic = "^2.6.1"
python-dotenv = "^1.0.1"
fastapi = "^0.109.2"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
asyncpg = "^0.29.0"
gunicorn = "^21.2.0"
sqlmodel = "^0.0.16"
sqlalchemy-utils = "^0.41.1"
sqlalchemy-json = "^0.7.0"
motor = "^3.3.2"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
